name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d5d4ca93922db21bbeb438a97d9b17975d19e394f00a781a7df92fd5ce91f19"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
