name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.15.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72d72ef846142d269bb70d189f1ed1e1713ab19cca009aa1be22ccdc9fb3dd1c"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
