name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.15.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94471e426dd6a9ad8f7513cba6d9d5869ced53b3866321d75be562bc81282ecb"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
