name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5aa70b21647a8acb6563ca84bc73488e61c76f564b758ca68abf17abc2c4aeea"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
