name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad526a6b532d3b7ce3e6a8ec33e56ddd00fe4016b70baceb08ff35f96068183f"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
