name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "838d5ad41602ff0a2948b023cdeefe992dbd6fab440ef57c919512be36359478"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
