name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf83a6a7e4530fd677291c0b38f2fc12a10f1e06fcdbedcc241383b7af749268"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
