name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de151ca61a6d591f395ad49a41e6c39ce1fd79128d4e0f5d2114693933668986"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
