name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa1599cf1857ce0fff668686fe0a0e5dc57cb9930b2d3c813707dc3d62b3fbea"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
