name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90596d163da21d980b3088efa2ef34a2338ddfc9953ce2c13fc5718fa310974c"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
