name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "339b575ce177459311d46e088dd1cab1cbe374cfa693779472e10ecd6fc2a56d"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
