name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a21985be88c9b9e717ab29dd3a9841b931314b39d83e41783930a2c66f12a9a5"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
