name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.8.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95cea06439c7c1ad905a8227d4a5ecd01c4431568bc277a122dcd074771fb254"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
