name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bbcfe9bfe76a33197a06ec1b94cb49ab44f4f45ef07ec2e445f01dd2067be40"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
