name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af1387c3404019ed73a688ddacfb07c9e2f6010423e00eb0376cd521f00cbbd0"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
