name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21b154e485e77e11e309808273ff4c8294f4c13c9d6388be721988d922cc182b"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
