name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63dacac6c781d6237ef125ae4719e74717239347f26373ff565b22329f4d2c41"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
