name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b12a8f897a431398f878f169cc698186c8a19387d552dce328f4c34fe90d32de"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
