name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.15.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8be19d6a12b45a6ad1e34fbf1236bcd54e8d12379d001346ce54f77aa32bd19e"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
