name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.16.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db2c80b1f208ef6503858cb690aabb73167bcfa74d7654e97244508fd089d93f"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
