name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06a4e3e72d907db0467d699a75ad61bfafc5ad0aaa6e40b6944c8842cb7c8032"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
