name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.15.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f935bd567e4e950565ddc43b85d0a9ea99762937e7d1737b518bbd7cc14ca5b5"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
