name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.17.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5af11d9fab6e0b1a39ea95276bf32946674d8da505abaf184300c82d370a50e"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
