#Whether these limitations will be imposed to players
limitations_imposed = true 

["Action Permissions"]
	permit_FastRun = true
	permit_ClimbUp = true
	permit_Roll = true
	permit_WallJump = false 
	permit_Dive = false 
	permit_HorizontalWallRun = false 
	permit_JumpFromBar = true
	permit_QuickTurn = false 
	permit_CatLeap = false 
	permit_Vault = true
	permit_WallSlide = true
	permit_BreakfallReady = false 
	permit_Dodge = false 
	permit_Slide = false 
	permit_Tap = true
	permit_Flipping = true
	permit_ClingToCliff = true 
	permit_Crawl = true
	permit_HangDown = true

[Stamina]
	#Limitation of max stamina recovery
	#Range: 1 ~ 10000
	max_value_of_stamina_recovery = 6 
	#Allow Infinite Stamina
	infinite_stamina = false 
	#Limitation of max stamina
	#Range: 300 ~ 100000
	max_value_of_stamina = 1000

	[Stamina."Least Consumption"]
		#Range: 0 ~ 10000
		stamina_consumption_of_WallJump = 120
		#Range: 0 ~ 10000
		stamina_consumption_of_WallSlide = 50
		#Range: 0 ~ 10000
		stamina_consumption_of_Vault = 100
		#Range: 0 ~ 10000
		stamina_consumption_of_CatLeap = 150
		#Range: 0 ~ 10000
		stamina_consumption_of_Dodge = 80
		#Range: 0 ~ 10000
		stamina_consumption_of_Slide = 15
		#Range: 0 ~ 10000
		stamina_consumption_of_BreakfallReady = 0
		#Range: 0 ~ 10000
		stamina_consumption_of_ClingToCliff = 2
		#Range: 0 ~ 10000
		stamina_consumption_of_Crawl = 15 
		#Range: 0 ~ 10000
		stamina_consumption_of_JumpFromBar = 100
		#Range: 0 ~ 10000
		stamina_consumption_of_Roll = 100
		#Range: 0 ~ 10000
		stamina_consumption_of_HangDown = 3
		#Range: 0 ~ 10000
		stamina_consumption_of_HorizontalWallRun = 50 
		#Range: 0 ~ 10000
		stamina_consumption_of_ClimbUp = 50
		#Range: 0 ~ 10000
		stamina_consumption_of_Flipping = 80
		#Range: 0 ~ 10000
		stamina_consumption_of_Tap = 100
		#Range: 0 ~ 10000
		stamina_consumption_of_FastRun = 10 
		#Range: 0 ~ 10000
		stamina_consumption_of_Dive = 0
		#Range: 0 ~ 10000
		stamina_consumption_of_QuickTurn = 0

