version: "3"

services:
  mc:
    image: itzg/minecraft-server:java8
    env_file: .env
    volumes:
      - "./minecraft-data:/data"
    environment:
      MODRINTH_PROJECT: my1CiIFD
      TYPE: MODRINTH
    ports:
      - 25565:25565
      - 24454:24454
    expose:
      - 24454:24454
