
#General mod settings
[general]
	#How often in seconds we set a random point around a player for mobs to wander to from far away. Makes mobs path around more, dont use if you have TPS performance issues.
	#Range: > -2147483648
	frequencyOfWanderingHordesPerPlayer = 30
	#Uses a different kind of mob alert noise, might break immersion a bit ;)
	soundUseAlternateAlertNoise = false
	#Spawn scent/blood sense sources for monsters to track
	awareness_Scent = true
	#Growling zombies attracts other zombies
	noisyZombies = true
	#How loud sounds should be for a mob targetting you
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	soundVolumeAlertTarget = 0.5
	#No comment
	soundInvestigates = true
	#Causes monsters to horde up and wander the surface together to random points
	wanderingHordes = true
	#Pistons cause sound sense sources attracting monsters
	noisyPistons = true
	#Spawn sound sense sources for monsters to track
	awareness_Sound = true
	#Monsters see light near player and move towards it
	awareness_Light = true
	#How loud sounds should be when you are alerted that a mob is coming to investigate an area near you
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	soundVolumeInvestigate = 0.4
	#Only spawn sound sense entities in Overworld
	awareness_Sound_OverworldOnly = false
	#No comment
	soundAlerts = true

