name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.10.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aeb30610c43bc19187c971a0933e4e5d694f0826a931ece330b1629e4ffc70a1"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
