name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56b8dcd4b4691b70a05c4e6326bbfac68689caa799131947227faf68667230bf"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
