name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c6f0d6b7336b97f3b0f2c7412c3804638013ba6bed2281bac718380e7b319ba"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
