name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e42a466e976f28219225bc8b4e5b6a08cdf1ac87253a058e2b9e1723a847b6b"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
