name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.10.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0219e16431e708ea8ef36ec24f3951f17f8db6392a18e3d72f4ccab48d84709a"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
