name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.10.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38be911c81572d0a11e644782995aeb766daf16df0e8c16af42a9da43a883777"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
