name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ef76c2bb3e7bfbfd500fa6a206104bc4cc820f7f5d309b0ecadefc9d8e948c1"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
