name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.10.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6c67adb6a259244df390f704136f8af67a8912feb46df16d1b12b4bbf886abf"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
